In [7]:
# %%
from loader.random_circle_loader import RandomCircleDataset
from loader.bptt import BPTTGraphLoader

dataset = RandomCircleDataset('data/random_circle/', subset='train', config='001')
# %%
loader = BPTTGraphLoader(dataset, batch_size=2, shuffle=False, seq_len=5)

data = next(iter(loader))

from models.TactiGraph_lstm import TactiGraph_lstm
from models.TactiGraph import TactiGraph
model = TactiGraph()


In [9]:
from torch_geometric.loader import DataLoader

loader = DataLoader(dataset, batch_size=1, shuffle=False)

for data in loader:
    print(data.x.shape)

torch.Size([1542, 1])
torch.Size([832, 1])
torch.Size([623, 1])
torch.Size([602, 1])
torch.Size([591, 1])
torch.Size([422, 1])
torch.Size([325, 1])
torch.Size([282, 1])
torch.Size([272, 1])
torch.Size([249, 1])
torch.Size([468, 1])
torch.Size([694, 1])
torch.Size([1604, 1])
torch.Size([3102, 1])
torch.Size([4466, 1])
torch.Size([4741, 1])
torch.Size([4981, 1])
torch.Size([4665, 1])
torch.Size([3583, 1])
torch.Size([3516, 1])
torch.Size([2454, 1])
torch.Size([1072, 1])
torch.Size([439, 1])
torch.Size([252, 1])
torch.Size([230, 1])
torch.Size([303, 1])
torch.Size([278, 1])
torch.Size([291, 1])
torch.Size([219, 1])
torch.Size([182, 1])
torch.Size([300, 1])
torch.Size([1139, 1])
torch.Size([2172, 1])
torch.Size([710, 1])
torch.Size([378, 1])
torch.Size([209, 1])
torch.Size([182, 1])
torch.Size([187, 1])
torch.Size([148, 1])
torch.Size([159, 1])
torch.Size([197, 1])
torch.Size([168, 1])
torch.Size([146, 1])
torch.Size([160, 1])
torch.Size([143, 1])
torch.Size([168, 1])
torch.Size([153, 1])


In [8]:
import torch

defective = torch.load('/home/hussain/me/projects/events_nn/data/random_circle/001/train/sample_01999.pt')
defective_1 = torch.load('/home/hussain/me/projects/events_nn/data/random_circle/001/val/sample_00512.pt')

In [20]:
defective_1()

torch.Size([105, 1])

In [10]:
defective_1.batch = torch.zeros_like(defective_1.x[:, 0])
defective_1

Data(x=[105, 1], edge_index=[2, 14], y=[1, 2], pos=[105, 3], edge_attr=[14, 3], batch=[105])

In [13]:
defective

Data(x=[30, 1], edge_index=[2, 0], y=[1, 2], pos=[30, 3], edge_attr=[0, 3])

In [12]:
model(defective_1)

/home/hussain/miniconda3/envs/tactile/lib/python3.8/site-packages/torch_geometric/nn/conv/spline_conv.py:133: UserWarning: We do not recommend using the non-optimized CPU version of `SplineConv`. If possible, please move your data to GPU.
  warnings.warn(


tensor([[0., 0.]])

In [4]:
out

(tensor([[[-0.0436, -0.1060, -0.0655,  ..., -0.2098,  0.0410, -0.0125],
          [ 0.1526,  0.0784, -0.1276,  ..., -0.1336,  0.0417, -0.0231]],
 
         [[ 0.0740, -0.0046, -0.1480,  ..., -0.0726,  0.0370, -0.0200],
          [-0.0684, -0.0466, -0.0611,  ..., -0.0931,  0.2019, -0.0131]],
 
         [[-0.0309, -0.0806, -0.0263,  ..., -0.0981,  0.1427, -0.0045],
          [ 0.1562,  0.0898,  0.1930,  ...,  0.0272,  0.0596, -0.1564]],
 
         [[ 0.1178, -0.0711,  0.3368,  ...,  0.0291, -0.1735, -0.3732],
          [ 0.0942,  0.0417, -0.0094,  ...,  0.0246,  0.4030, -0.0076]],
 
         [[ 0.0499, -0.1277, -0.0117,  ..., -0.0018,  0.5490, -0.0105],
          [ 0.0055, -0.2056, -0.0058,  ..., -0.0650,  0.4243, -0.0611]]],
        grad_fn=<StackBackward0>),
 (tensor([[[ 0.0499, -0.1277, -0.0117,  ..., -0.0018,  0.5490, -0.0105],
           [ 0.0055, -0.2056, -0.0058,  ..., -0.0650,  0.4243, -0.0611]]],
         grad_fn=<StackBackward0>),
  tensor([[[ 0.7160, -0.2534, -0.0871,  ..., -0

In [ ]:
from torch_geometric.data import Data, Batch
from torch_geometric.data.collate import collate

b_0= collate(Batch, data[0])
b_1= collate(Batch, data[1])
collate(Batch, [b_0, b_1])

AttributeError: 'tupleBatch' object has no attribute 'stores_as'